from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 812)
        MainWindow.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_image = QtWidgets.QPushButton(self.centralwidget)
        self.load_image.setGeometry(QtCore.QRect(10, 130, 331, 41))
        self.load_image.setStyleSheet("color: rgb(255, 255, 255);")
        self.load_image.setObjectName("load_image")
        self.segmentation = QtWidgets.QPushButton(self.centralwidget)
        self.segmentation.setGeometry(QtCore.QRect(10, 190, 331, 41))
        self.segmentation.setStyleSheet("color: rgb(255, 255, 255);")
        self.segmentation.setObjectName("segmentation")
        self.save_image = QtWidgets.QPushButton(self.centralwidget)
        self.save_image.setGeometry(QtCore.QRect(10, 250, 331, 41))
        self.save_image.setStyleSheet("color: rgb(255, 255, 255);")
        self.save_image.setObjectName("save_image")
        self.segments_frame = QtWidgets.QFrame(self.centralwidget)
        self.segments_frame.setGeometry(QtCore.QRect(10, 300, 330, 460))
        self.segments_frame.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.segments_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.segments_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.segments_frame.setObjectName("segments_frame")
        self.add_segment = QtWidgets.QPushButton(self.segments_frame)
        self.add_segment.setGeometry(QtCore.QRect(10, 10, 131, 41))
        self.add_segment.setObjectName("add_segment")
        self.delete_segment = QtWidgets.QPushButton(self.segments_frame)
        self.delete_segment.setGeometry(QtCore.QRect(190, 10, 131, 41))
        self.delete_segment.setObjectName("delete_segment")
        self.segments_table = QtWidgets.QTableWidget(self.segments_frame)
        self.segments_table.setGeometry(QtCore.QRect(10, 60, 311, 391))
        self.segments_table.setAutoScroll(True)
        self.segments_table.setShowGrid(True)
        self.segments_table.setObjectName("segments_table")
        self.segments_table.setColumnCount(3)
        self.segments_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("src/closed_eye.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("src/eye.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("src/closed_eye.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("src/eye.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("src/closed_eye.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.segments_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.segments_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setItem(0, 2, item)
        self.images_widget = QtWidgets.QWidget(self.centralwidget)
        self.images_widget.setGeometry(QtCore.QRect(350, 130, 750, 630))
        self.images_widget.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.images_widget.setObjectName("images_widget")
        self.x_axis = QtWidgets.QWidget(self.images_widget)
        self.x_axis.setGeometry(QtCore.QRect(0, 0, 375, 315))
        self.x_axis.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.x_axis.setObjectName("x_axis")
        self.slider_x = QtWidgets.QSlider(self.x_axis)
        self.slider_x.setGeometry(QtCore.QRect(10, 10, 201, 21))
        self.slider_x.setStyleSheet("color: rgb(255, 0, 0);")
        self.slider_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_x.setObjectName("slider_x")
        self.label_x = QtWidgets.QLabel(self.x_axis)
        self.label_x.setGeometry(QtCore.QRect(220, 10, 41, 16))
        self.label_x.setObjectName("label_x")
        self.y_axis = QtWidgets.QWidget(self.images_widget)
        self.y_axis.setGeometry(QtCore.QRect(0, 320, 375, 315))
        self.y_axis.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.y_axis.setObjectName("y_axis")
        self.slider_y = QtWidgets.QSlider(self.y_axis)
        self.slider_y.setGeometry(QtCore.QRect(10, 10, 201, 21))
        self.slider_y.setStyleSheet("color: rgb(255, 0, 0);")
        self.slider_y.setOrientation(QtCore.Qt.Horizontal)
        self.slider_y.setObjectName("slider_y")
        self.label_y = QtWidgets.QLabel(self.y_axis)
        self.label_y.setGeometry(QtCore.QRect(220, 10, 41, 16))
        self.label_y.setObjectName("label_y")
        self.third_dim_widget = QtWidgets.QWidget(self.images_widget)
        self.third_dim_widget.setGeometry(QtCore.QRect(380, 0, 375, 315))
        self.third_dim_widget.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.third_dim_widget.setObjectName("third_dim_widget")
        self.z_axis = QtWidgets.QWidget(self.images_widget)
        self.z_axis.setGeometry(QtCore.QRect(380, 320, 375, 315))
        self.z_axis.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.z_axis.setObjectName("z_axis")
        self.slider_z = QtWidgets.QSlider(self.z_axis)
        self.slider_z.setGeometry(QtCore.QRect(10, 10, 201, 21))
        self.slider_z.setStyleSheet("color: rgb(255, 0, 0);")
        self.slider_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_z.setObjectName("slider_z")
        self.label_z = QtWidgets.QLabel(self.z_axis)
        self.label_z.setGeometry(QtCore.QRect(220, 10, 41, 16))
        self.label_z.setObjectName("label_z")
        self.save_report = QtWidgets.QPushButton(self.centralwidget)
        self.save_report.setGeometry(QtCore.QRect(940, 0, 161, 121))
        self.save_report.setStyleSheet("color: rgb(255, 255, 255);")
        self.save_report.setObjectName("save_report")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сегментация опухоли мозга"))
        self.load_image.setText(_translate("MainWindow", "Загрузить изображение"))
        self.segmentation.setText(_translate("MainWindow", "Запустить сегментацию"))
        self.save_image.setText(_translate("MainWindow", "Сохранить сегментацию"))
        self.add_segment.setText(_translate("MainWindow", "Добавить сегмент"))
        self.delete_segment.setText(_translate("MainWindow", "Удалить сегмент"))
        self.segments_table.setSortingEnabled(True)
        item = self.segments_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.segments_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Видимость"))
        item = self.segments_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Цвет"))
        item = self.segments_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сегмент"))
        __sortingEnabled = self.segments_table.isSortingEnabled()
        self.segments_table.setSortingEnabled(False)
        item = self.segments_table.item(0, 2)
        item.setText(_translate("MainWindow", "ядро опухоли"))
        self.segments_table.setSortingEnabled(__sortingEnabled)
        self.label_x.setText(_translate("MainWindow", "Cлой:"))
        self.label_y.setText(_translate("MainWindow", "Слой:"))
        self.label_z.setText(_translate("MainWindow", "Слой:"))
        self.save_report.setText(_translate("MainWindow", "Сохранить отчёт"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())